apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: myapp-relicaset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
      type: back-end
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
    